### ISSUE TITLE
Bad name for Hana Taaka Daka!

### ISSUE THREAD

**Issue by mgsx-dev** [libretro-thumbnails/NEC_-_PC_Engine_-_TurboGrafx_16#2]
Sorry, I don't know if it's the right place but i just wanted to report that **Hana Taaka Daka!** pictures names differ from libretro database rom name : **Hana Taka Daka!.png** (database name seams to be the right one)

**Comment by RobLoach** [comment]
Thanks! We target No-Intro:
https://github.com/libretro/libretro-database/blob/master/metadat/no-intro/NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016.dat#L891

Looks like Taka, with one a, is referenced from the metadata folders. Those are not really well maintained.

**Comment by RobLoach** [comment]
I think this is fixed.
