### ISSUE TITLE
TurboGrafx-16 is usually spelled with a hyphen. The Retroarch thumbnail folder probably should follow?

### ISSUE THREAD

**Issue by Khronikos** [libretro-thumbnails/NEC_-_PC_Engine_-_TurboGrafx_16#7]
Just a small issue I saw. Wiki and other sources like Amazon all use a hyphen. The CD portion of thumbs also uses a hyphen to separate the identifier. Obviously, not a big deal was just going over this after redoing my rom set.

**Comment by RobLoach** [comment]
We follow No-Intro naming....
https://datomatic.no-intro.org

`NEC - PC Engine - TurboGrafx 16`

**Comment by Khronikos** [comment]
Oh I see. Is that actually correct though? I'm just curious as I am not sure how this is supposed to be. I wish people would align their standards lol.

**Comment by RobLoach** [comment]
Whether or not it's correct, it's what we're following :wink:

Their forum is really active: https://forum.no-intro.org ..... Feel free to shoot up a thread there to see if people would like to switch. They've switched their naming scheme before, so it wouldn't be out of the norm.
